#!/bin/sh

if [ ! -f "/etc/firstboot" ]; then 
    echo "root:x:0:0:root:/root:/bin/sh" > /etc/passwd
    echo "root:x:0:" > /etc/group
    echo "root::10933:0:99999:7:::" > /etc/shadow
    echo "root:root" | chpasswd
fi

mount -t proc none /proc
mount -t tmpfs none /tmp
mount -t devtmpfs devtmpfs /dev
mount -t sysfs sysfs /sys

mkdir -p /var/run /var/log /var/tmp
mkdir -p /etc/network /etc/ssh

mknod /dev/random c 1 8
mknod /dev/urandom c 1 9

if [ ! -f "/etc/firstboot" ]; then
    ln -sf /usr/share/zoneinfo/America/Los_Angeles /etc/localtime
fi

export PATH=$PATH:/usr/libexec/gcc/i586-linux-uclibc/4.6.1:/opt/nodejs/bin
export PS1='[\[\e[1;33m\]\u@\h\[\e[0m\]] (\[\e[1;36m\]$(date "+%T")\[\e[0m\]) \[\e[1;34m\]\w\[\e[0m\]\[\e[1;32m\]\$\[\e[0m\] '

if [ ! -f "/etc/firstboot" ]; then
    echo "auto eth0" >> /etc/network/interfaces
    echo "iface eth0 inet dhcp" >> /etc/network/interfaces
fi

if [ ! -f "/etc/firstboot" ]; then
    echo "nameserver 8.8.8.8" > /etc/resolv.conf
    echo "nameserver 8.8.4.4" >> /etc/resolv.conf
fi

dmesg -n 3

if [ ! -f "/etc/firstboot" ]; then
    echo "chickadeeOS" > /etc/hostname
    hostname $(cat /etc/hostname)

    touch /etc/firstboot
fi

clear

# echo -e $(cat /etc/matthewyang204.ascii) | cat
cat /etc/motd
echo "chickadeeOS (version 0.0.1) [" $(uname -r) "]"
echo

# /bin/sh +m
exec cttyhack /bin/sh

